services:
  apache:
    build:
      context: .
      dockerfile: .docker/php${PHP_VERSION}/DockerFile
    container_name: lamp_8
    ports:
      - ${APACHE_PORT}:80

    networks:
      public_net:
        ipv4_address: ${MY_IP}.10
      web_net:
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${PHP_INI}/php.ini:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${VHOSTS_DIR}:/etc/apache2/sites-available
      - ${APACHE_LOG_DIR}:/var/log/apache2
    
    restart: always

# volumes:
#   mysql_data:

networks:
  public_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: ${MY_IP}.0/24
  web_net:
    driver: bridge
